# Generated by Django 4.1.3 on 2022-11-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('dados', models.CharField(max_length=150)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=4)),
            ],
        ),
    ]
